### ISSUE TITLE
Checksum error

### ISSUE THREAD

**Issue by NoRulesJustFeels** [kitschpatrol/Brain#10]
I have hacked my Mattel MindFlex using these instructions: http://frontiernerds.com/brain-hack

I'm printing the readCSV and readErrors:
80,0,0,181761,359220,55384,11126,48659,361307,168113,37803
ERROR: Checksum

I always get 0 for both readSignalQuality and readAttention.

Any help would be appreciated.

**Comment by bcaller** [comment]
Did you ever fix this? I'm getting it now.

**Comment by kitschpatrol** [comment]
This means the checksum on the packet failed, which points to bad serial data from the TGAM. Closing as this thread is quite all. : )
