### ISSUE TITLE
Few seconds of data, Then cuts to 200, 0, 0

### ISSUE THREAD

**Issue by zombodotcom** [kitschpatrol/Brain#14]
Hey, I got a mindflex duel, so 2 headsets, I'm only testing one headset so far, I turn the headset on and I can get data for a few seconds on the braingrapher with an arduino, then I'm getting 200,0,0 some other guy had the same question and I asked him on twitter with one question and he blocked me for some reason? 
I get a few seconds of data every time I turn it on and off again then it cuts out to 200,0,0

Any ideas ? I'll try the other headset when I have time

**Comment by kitschpatrol** [comment]
Sounds like connection issues, please see issue #12.
