### ISSUE TITLE
problem with arduino brain library serial monitor

### ISSUE THREAD

**Issue by ancymathai** [kitschpatrol/Brain#16]
it is the project shown here : http://frontiernerds.com/brain-hack 
when it is time to start getting data in serial monitor it just shows nothing...
i double checked the connections i soldered and everything is good...
the code is this :

// Arduino Brain Library - Brain Serial Test

// Description: Grabs brain data from the serial RX pin and sends CSV out over the TX pin (Half duplex.)
// More info: https://github.com/kitschpatrol/Arduino-Brain-Library
// Author: Eric Mika, 2010 revised in 2014

#include

// Set up the brain parser, pass it the hardware serial object you want to listen on.
Brain brain(Serial);

void setup() {
// Start the hardware serial.
Serial.begin(9600);
}

void loop() {
// Expect packets about once per second.
// The .readCSV() function returns a string (well, char*) listing the most recent brain data, in the following format:
// "signal strength, attention, meditation, delta, theta, low alpha, high alpha, low beta, high beta, low gamma, high gamma"

if (brain.update()) {
Serial.println(brain.readErrors());
Serial.println(brain.readCSV());
}
}

I used Roboduino--arduino-1.0.1

some times comming like given below

![untitledd](https://cloud.githubusercontent.com/assets/13223156/11861050/26dcc6da-a4a2-11e5-8931-9ea44a5f4ef2.png)

**Comment by molavy** [comment]
i have exactly problem, 
when i connect t pin to tx i give one line no meaning characters,
when connect  t pin to rx i give no data
i using Thinkgear Am Development Start Kit

**Comment by PCDotFan** [comment]
Me, too. I used Arduino UNO R3 and didn't see anything in Serial Monitor..

**Comment by PCDotFan** [comment]
@molavy Ahh..It works, plz select "57600 Baud" and don't forget to replace "Serial.begin(9600)"

**Comment by ancymathai** [comment]
its not the serial data ......its only seen when reset button is pressed........

when replaced the arduino board problem solved
