### ISSUE TITLE
Processing tells me no connection even though serial monitor works just fine

### ISSUE THREAD

**Issue by SaReichlSa** [kitschpatrol/Brain#17]
hello guys, 
I am in a quite urgent problem. 
I used the mind flex already before and it worked just fine. 
After 3 month I wanted to open the project again. My problem now is that Arduino worked fine, the serial monitor shows me that the connection is good ( drops to 0) but when I open the code in Processing it won't show me anything ( red light, packages received = 0)

NEED HELP!!!

Ps: I am working with Arduino Uno and Processing 2.2.1

**Comment by kitschpatrol** [comment]
Are you setting the correct serial port in the processing sketch?

See this line:
https://github.com/kitschpatrol/BrainGrapher/blob/master/BrainGrapher/BrainGrapher.pde#L40
