### ISSUE TITLE
Adding opto-isolater to mindflex

### ISSUE THREAD

**Issue by r-bt** [kitschpatrol/Brain#18]
Hi all, I have a mindflex headset which I have set up according to this tutorial(http://www.frontiernerds.com/brain-hack) however the signal strength never reaches 0 and as such I cannot get the attention/meditation values. I tried adding salt water and that worked for a while but ultimately it stopped. So I purchased and opto-isolator(http://www.maplin.ie/p/high-voltage-opto-isolator-ay44x) but I am stuck at how I am meant to wire it up to the arduino and minflex. 

Any help would be greatly appreciated. 
Richard

**Comment by ribas9521** [comment]
I would like to know too!

**Comment by sixtyfive** [comment]
how would an optoisolator solve _that_ problem?

**Comment by kitschpatrol** [comment]
Closing this as it's not related to a specific issue with the.

Perhaps an opto-isolator it could prevent noise between the Arduino and the TGAM, but given everything that's already going on right on the TGAM board, that seems a bit a bit superstitious.
