### ISSUE TITLE
TGAM module rev 2.7

### ISSUE THREAD

**Issue by penco193** [kitschpatrol/Brain#19]
Hi!, i have a mindflex game with ThinkGear module rev 2.7. any of you can tell me if the firmware version is 1.6 or 1.7 for this board?, or where could i find it?. any help will be appreciated

**Comment by faogustavo** [comment]
@penco193 did you solved this?

**Comment by penco193** [comment]
Yes, thanks!

**Comment by faogustavo** [comment]
Can you tell me how? I am with the same problem :/

**Comment by sixtyfive** [comment]
fwiw, i have a `TGAM1_R2.8` that i've not yet been able to make work with `Brain`... not sure if the board revision is any kind of problem as it's still supposed to send the same data via the same pin, right?

**Comment by 3Dtj** [comment]
I seem to be having the same issue in getting data using the Brain sketch.  Will double check TX connection and library.

**Comment by sixtyfive** [comment]
@3Dtj I ended up sort-of rolling my own as I couldn't figure out what was wrong. If you wanna give it a go: https://github.com/sixtyfive/tgam1

**Comment by 3Dtj** [comment]
Thanks brother.  I'll give it a go and see if it works out,

**Comment by kitschpatrol** [comment]
Thanks — unfortunately I don't have access to the 2.7+ module to test against this library.
