### ISSUE TITLE
brain

### ISSUE THREAD

**Issue by PeerapongSrisathan** [kitschpatrol/Brain#32]
Hello, just when I do a project about Brain to command the car through matlab program, which now is attached to the reading program from the library that uses 57600 which
The resulting values are like this
![2023-02-16](https://user-images.githubusercontent.com/116908449/221162184-36197fc5-443f-42af-abe9-68edfb5d9978.png)

**Comment by kitschpatrol** [comment]
Looks like you're not getting a good connection (the first value in the CSV never goes to 0).
