### ISSUE TITLE
Contradictory language in README

### ISSUE THREAD

**Issue by Archonic944** [kitschpatrol/Brain#33]
From the README:
> Signal strength ranges from 0 - 200. Counterintuitively, 0 means the unit has connected successfully, and 200 means there is no signal.

Also from the README:
>` byte readSignalQuality();`
Returns the latest signal quality reading. 200 is high, 0 is no signal.

This is really confusing.

**Comment by kitschpatrol** [comment]
Good catch, fixed. The first section is correct: 200 is no signal, 0 is good signal.
