### ISSUE TITLE
Force Trainer II Support

### ISSUE THREAD

**Issue by Archonic944** [kitschpatrol/Brain#34]
This repository seems to only work with Force Trainer I. When tried with the Force Trainer II, signal strength fluctuated rapidly from 200 to 55, even when correcting the baud rate.

**Comment by kitschpatrol** [comment]
Thanks, this could either be a connection issue (unrelated to the library), or perhaps the  Force Trainer II uses a different protocol (which would mean it won't work with the library).

I don't have a Force Trainer II to test with, so I can't verify compatibility.

I've [updated the documentation to clarify compatible hardware](https://github.com/kitschpatrol/Brain#compatibility).
