### ISSUE TITLE
Concept explanation please

### ISSUE THREAD

**Issue by Melonmanyeah** [kitschpatrol/Brain#35]
yeah so i want to understand the concept how is this library work? So the neurosky T pin send 3 data signal quality meditation and attention in 1 wire right. I have try normal Serial.print() and i got some random values like 14 15 55 is that the average of the serial input or the bits didnt determine yet so it got random values? 

1. What protocol is this use to communicate is the EEG chip use UART too?
2. How to decode that information (concept of decoding) like do we have to determine its waiting rate for each pack of 3 values ?
3. How to make meditation and attention the raw wave of the brain?
4. Rx pin need to plug in after uploaded the code right?

**Comment by kitschpatrol** [comment]
For more on the overall approach and components involved, please see the article here:
https://frontiernerds.com/brain-hack

As for the concept and operation of the library itself, it's just a [couple hundred lines of code](https://github.com/kitschpatrol/Brain/blob/master/Brain.cpp) — skimming through this should give you a sense of how the raw protocol from the headset is parsed and then provided through a simplified interface.
