### ISSUE TITLE
No Attention or Meditation visible on Grapher

### ISSUE THREAD

**Issue by blueforjack** [kitschpatrol/Brain#36]
Hello, 

I was wondering if you could assist me as the ATTENTION and Meditation columns have no reaction whilst running, compared to all other columns. Please see the attached for a visual representation.

I'm using Processing 2.2.1

Also I would like to note that my connection quality has always been yellow.

Any information you could provide would be much appreciated!

Many thanks,
Jack.

![Grapher](https://github.com/kitschpatrol/Brain/assets/161144017/7d14eb51-f61d-4d5d-a06c-f2b5a6347aad)

**Comment by kitschpatrol** [comment]
Hi Jack, attention and meditation values are only provided when the connection quality is "good" (green in the grapher UI, or a value of "0" in the packet from the device).

Here are some connection troubleshooting tips from NeuroSky:
http://support.neurosky.com/kb/mindwave-mobile-2/cant-get-good-eeg-signal
